import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Header from "../Components/Header";
import Categories from "../Components/Categories";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Lekhok</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="flex">
          <div className="flex place-items-center">
            <div>
              <h1 className="text-2xl">Lekhok</h1>
            </div>
            <div className="flex ml-96 space-x-3">
              <Link href="/login">
                <button className="p-3 bg-slate-800 text-white rounded-xl">
                  Log In
                </button>
              </Link>
              <Link href="/register">
                <button className="p-3 bg-slate-800 text-white rounded-xl">
                  Register
                </button>
              </Link>
            </div>
          </div>
        </section>
        <Categories />
      </main>
    </>
  );
}
